# Generated by Django 2.2.6 on 2019-10-30 15:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_album_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Field',
            new_name='Files',
        ),
    ]
